name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - seaborn
  - bqplot
  - ipywidgets
  - geopandas
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
